name: "Load Strimzi images"
description: "Load Strimzi images"

inputs:
  architecture:
    description: "Architecture"
    required: false
    default: "amd64"
  localRegistry:
    description: "Flag for using local registry as images destination"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: containers-${{ inputs.architecture }}.tar

    - name: "Untar the ${{ inputs.architecture }} containers"
      shell: bash
      run: tar -xvf containers-${{ inputs.architecture }}.tar

    - name: "Delete the original archive with the ${{ inputs.architecture }} containers"
      shell: bash
      run: rm containers-${{ inputs.architecture }}.tar

    # This is for loading images into local registry
    - name: Load & push Strimzi images into local registry
      shell: bash
      if: ${{ contains(inputs.localRegistry, 'true') }}
      run: |
        make docker_load docker_e2e docker_delete_archive
      env:
        DOCKER_ARCHITECTURE: ${{ inputs.architecture }}

    # This is for loading images into external registry
    - name: Load & push Strimzi images external registry
      shell: bash
      if: ${{ !contains(inputs.localRegistry, 'true') }}
      run: |
        make docker_load docker_tag docker_push docker_delete_archive
      env:
        DOCKER_ARCHITECTURE: ${{ inputs.architecture }}

    - name: List built images
      if: ${{ always() }}
      shell: bash
      run: |
        docker images -a